In [2]:
import numpy as np
from numpy import genfromtxt
from sklearn import linear_model
import matplotlib.pyplot as plt

In [3]:
# 读入数据
data = genfromtxt(r"DElivery.csv", delimiter = ",")
print(data)

[[100.    4.    9.3]
 [ 50.    3.    4.8]
 [100.    4.    8.9]
 [100.    2.    6.5]
 [ 50.    2.    4.2]
 [ 80.    2.    6.2]
 [ 75.    3.    7.4]
 [ 65.    4.    6. ]
 [ 90.    3.    7.6]
 [ 90.    2.    6.1]]


In [4]:
# 切分数据
x_data = data[:,:-1]
y_data = data[:,-1]
print(x_data)
print(y_data)

[[100.   4.]
 [ 50.   3.]
 [100.   4.]
 [100.   2.]
 [ 50.   2.]
 [ 80.   2.]
 [ 75.   3.]
 [ 65.   4.]
 [ 90.   3.]
 [ 90.   2.]]
[9.3 4.8 8.9 6.5 4.2 6.2 7.4 6.  7.6 6.1]


In [5]:
# 创建模型
model = linear_model.LinearRegression()
model.fit(x_data, y_data)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
# 系数
print("coefficients:",model.coef_)

# 截距
print("intercept", model.intercept_)

#测试
x_test = [[102, 4]]
predict = model.predict(x_test)
print("predict:",predict)

coefficients: [0.0611346  0.92342537]
intercept -0.8687014667817126
predict: [9.06072908]
